### ISSUE TITLE
Push Gateway module can't be found on Maven Central

### ISSUE THREAD

**Issue by n-raymond** [ChristopherDavenport/epimetheus-http4s#158]
Hi !

Firstly, thanks a lot for this great work ! I am pretty excited to use Prometheus in a pure functionnal way !

I would like to use `epimetheus` library in a use case where I need to push metrics to a push gateway but I have been surprised not to find this part of the project on Maven Central.

Since `epimetheus-http4s-pushgateway` project is not aggregated in the root project, I guess that this is not published by the `sbt-ci-release` plugin. Is this something desired ?

**Comment by ChristopherDavenport** [comment]
Oh goodness, thats a total mistake. thanks for raising this to my attention!

**Comment by ChristopherDavenport** [comment]
[0.4.2](https://github.com/ChristopherDavenport/epimetheus-http4s/releases/tag/v0.4.2) should be on it way to maven central

https://travis-ci.com/github/ChristopherDavenport/epimetheus-http4s/jobs/364080096
